# -*- coding: utf-8 -*-
"""MachineLearning2nd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAoJnO3zHm95oEAOhRL_qN6YEmSLIjXl
"""

# 1ο ερώτημα (ΚΟΙΝΟ)
from tensorflow.keras.datasets import fashion_mnist

# Φόρτωση δεδομένων Fashion-MNIST
(x_train_full, y_train_full), (x_test, y_test) = fashion_mnist.load_data()

print(f"Training samples: {x_train_full.shape[0]}, Test samples: {x_test.shape[0]}")

# 2ο ερώτημα (ΚΟΙΝΟ)
# Εισαγωγή βιβλιοθηκών
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from sklearn.model_selection import train_test_split

# Φόρτωση του Fashion-MNIST dataset
(x_train_full, y_train_full), (x_test, y_test) = fashion_mnist.load_data()

# Κανονικοποίηση δεδομένων
x_train_full = x_train_full / 255.0
x_test = x_test / 255.0

# Διαχωρισμός του train set σε train και validation set
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full, test_size=0.2, random_state=42
)

# Εμφάνιση πληροφοριών για τα σύνολα δεδομένων
print("Train set shape:", x_train.shape, y_train.shape)
print("Validation set shape:", x_val.shape, y_val.shape)
print("Test set shape:", x_test.shape, y_test.shape)

#3o ερώτημα για PCA
from sklearn.decomposition import PCA

# Flatten the image data for PCA
x_train_flattened = x_train.reshape(x_train.shape[0], -1)
x_val_flattened = x_val.reshape(x_val.shape[0], -1)
x_test_flattened = x_test.reshape(x_test.shape[0], -1)

# Apply PCA to reduce dimensions (e.g., retain 95% variance)
pca = PCA(n_components=0.95, random_state=42)
x_train_pca = pca.fit_transform(x_train_flattened)
x_val_pca = pca.transform(x_val_flattened)
x_test_pca = pca.transform(x_test_flattened)

# Print the explained variance ratio
print("Explained variance ratio (sum):", sum(pca.explained_variance_ratio_))
print("Reduced dimension:", x_train_pca.shape[1])

# Display shapes after PCA transformation
print("PCA transformed train shape:", x_train_pca.shape)
print("PCA transformed validation shape:", x_val_pca.shape)
print("PCA transformed test shape:", x_test_pca.shape)

#4o ερώτημα για PCA
import matplotlib.pyplot as plt
import numpy as np

# Function to get random images for each class
def get_random_images_per_class(x_data, y_data, classes=10):
    selected_images = []
    for class_label in range(classes):
        indices = np.where(y_data == class_label)[0]
        random_index = np.random.choice(indices)
        selected_images.append(x_data[random_index])
    return np.array(selected_images)

# Get random images from the test set (one for each class)
random_images = get_random_images_per_class(x_test, y_test)

# Reconstruct images using PCA (if the technique allows it)
random_images_flattened = random_images.reshape(random_images.shape[0], -1)
reconstructed_images_flattened = pca.inverse_transform(pca.transform(random_images_flattened))
reconstructed_images = reconstructed_images_flattened.reshape(random_images.shape)

# Plot original and reconstructed images side by side
fig, axes = plt.subplots(2, 10, figsize=(20, 5))
for i in range(10):
    # Original image
    axes[0, i].imshow(random_images[i], cmap="gray")
    axes[0, i].set_title(f"Class {i}")
    axes[0, i].axis("off")

    # Reconstructed image
    axes[1, i].imshow(reconstructed_images[i], cmap="gray")
    axes[1, i].set_title(f"Reconstructed {i}")
    axes[1, i].axis("off")

plt.tight_layout()
plt.show()

#5o ερώτημα για PCA
# Plot the cumulative explained variance ratio
explained_variance_ratio_cumsum = np.cumsum(pca.explained_variance_ratio_)

plt.figure(figsize=(8, 5))
plt.plot(
    range(1, len(explained_variance_ratio_cumsum) + 1),
    explained_variance_ratio_cumsum,
    marker="o",
    linestyle="--",
    color="b"
)
plt.title("Cumulative Explained Variance Ratio by PCA Components")
plt.xlabel("Number of Principal Components")
plt.ylabel("Cumulative Explained Variance")
plt.axhline(y=0.95, color="r", linestyle="--", label="95% Variance Threshold")
plt.axvline(x=x_train_pca.shape[1], color="g", linestyle="--", label=f"{x_train_pca.shape[1]} Components")
plt.legend(loc="best")
plt.grid()
plt.show()

#6o ερώτημα για PCA
# Encode the test data using the trained PCA model
x_test_encoded = pca.transform(x_test_flattened)

# Display the shape of the encoded test data
print("Original test data shape:", x_test_flattened.shape)
print("Encoded test data shape:", x_test_encoded.shape)

#7o ερώτημα για PCA
from sklearn.cluster import MiniBatchKMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score

# MiniBatch KMeans clustering
kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
kmeans_labels = kmeans.fit_predict(x_test_encoded)

# DBSCAN clustering
dbscan = DBSCAN(eps=3, min_samples=5)  # Hyperparameters may require tuning
dbscan_labels = dbscan.fit_predict(x_test_encoded)

# Agglomerative Clustering
agglomerative = AgglomerativeClustering(n_clusters=10)
agglomerative_labels = agglomerative.fit_predict(x_test_encoded)

# Print cluster counts
print("MiniBatch KMeans Clusters:", len(set(kmeans_labels)) - (1 if -1 in kmeans_labels else 0))

print("\nDBSCAN Clusters:", len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0))

print("\nAgglomerative Clustering Clusters:", len(set(agglomerative_labels)) - (1 if -1 in agglomerative_labels else 0))

#8o ερώτημα για PCA
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score, adjusted_mutual_info_score

# Compute metrics for MiniBatch KMeans
print("MiniBatch KMeans Metrics:")
print("Calinski-Harabasz Index:", calinski_harabasz_score(x_test_encoded, kmeans_labels))
print("Davies-Bouldin Index:", davies_bouldin_score(x_test_encoded, kmeans_labels))
print("Silhouette Score:", silhouette_score(x_test_encoded, kmeans_labels))
print("Adjusted Mutual Information (AMI):", adjusted_mutual_info_score(y_test, kmeans_labels))

# Compute metrics for DBSCAN (if more than one cluster is formed)
print("\nDBSCAN Metrics:")
if len(set(dbscan_labels)) > 1:
    print("Calinski-Harabasz Index:", calinski_harabasz_score(x_test_encoded, dbscan_labels))
    print("Davies-Bouldin Index:", davies_bouldin_score(x_test_encoded, dbscan_labels))
    print("Silhouette Score:", silhouette_score(x_test_encoded, dbscan_labels))
    print("Adjusted Mutual Information (AMI):", adjusted_mutual_info_score(y_test, dbscan_labels))
else:
    print("DBSCAN formed only one cluster; metrics are not applicable.")

# Compute metrics for Agglomerative Clustering
print("\nAgglomerative Clustering Metrics:")
print("Calinski-Harabasz Index:", calinski_harabasz_score(x_test_encoded, agglomerative_labels))
print("Davies-Bouldin Index:", davies_bouldin_score(x_test_encoded, agglomerative_labels))
print("Silhouette Score:", silhouette_score(x_test_encoded, agglomerative_labels))
print("Adjusted Mutual Information (AMI):", adjusted_mutual_info_score(y_test, agglomerative_labels))

#9o ερώτημα για PCA
import pandas as pd
import time
from sklearn.metrics import adjusted_mutual_info_score

# Initialize a DataFrame to store the results
results_df = pd.DataFrame(columns=[
    "Dimensionality Reduction",
    "Clustering Algorithm",
    "Dim. Red. Training Time (s)",
    "Clustering Execution Time (s)",
    "Number of Clusters",
    "Calinski-Harabasz Index",
    "Davies-Bouldin Index",
    "Silhouette Score",
    "Adjusted Mutual Information (AMI)"
])

# Measure training time for PCA
dim_red_start = time.time()
x_test_encoded = pca.transform(x_test_flattened)
dim_red_time = time.time() - dim_red_start

# MiniBatch KMeans
clustering_start = time.time()
kmeans_labels = kmeans.fit_predict(x_test_encoded)
clustering_time = time.time() - clustering_start

# Compute metrics for MiniBatch KMeans
results_df = pd.concat([results_df, pd.DataFrame([{
    "Dimensionality Reduction": "PCA",
    "Clustering Algorithm": "MiniBatch KMeans",
    "Dim. Red. Training Time (s)": dim_red_time,
    "Clustering Execution Time (s)": clustering_time,
    "Number of Clusters": len(set(kmeans_labels)),
    "Calinski-Harabasz Index": calinski_harabasz_score(x_test_encoded, kmeans_labels),
    "Davies-Bouldin Index": davies_bouldin_score(x_test_encoded, kmeans_labels),
    "Silhouette Score": silhouette_score(x_test_encoded, kmeans_labels),
    "Adjusted Mutual Information (AMI)": adjusted_mutual_info_score(y_test, kmeans_labels)
}])], ignore_index=True)

# DBSCAN
clustering_start = time.time()
dbscan_labels = dbscan.fit_predict(x_test_encoded)
clustering_time = time.time() - clustering_start

# Compute metrics for DBSCAN
if len(set(dbscan_labels)) > 1:  # Ensure more than one cluster
    results_df = pd.concat([results_df, pd.DataFrame([{
        "Dimensionality Reduction": "PCA",
        "Clustering Algorithm": "DBSCAN",
        "Dim. Red. Training Time (s)": dim_red_time,
        "Clustering Execution Time (s)": clustering_time,
        "Number of Clusters": len(set(dbscan_labels)),
        "Calinski-Harabasz Index": calinski_harabasz_score(x_test_encoded, dbscan_labels),
        "Davies-Bouldin Index": davies_bouldin_score(x_test_encoded, dbscan_labels),
        "Silhouette Score": silhouette_score(x_test_encoded, dbscan_labels),
        "Adjusted Mutual Information (AMI)": adjusted_mutual_info_score(y_test, dbscan_labels)
    }])], ignore_index=True)

# Agglomerative Clustering
clustering_start = time.time()
agglomerative_labels = agglomerative.fit_predict(x_test_encoded)
clustering_time = time.time() - clustering_start

# Compute metrics for Agglomerative Clustering
results_df = pd.concat([results_df, pd.DataFrame([{
    "Dimensionality Reduction": "PCA",
    "Clustering Algorithm": "Agglomerative Clustering",
    "Dim. Red. Training Time (s)": dim_red_time,
    "Clustering Execution Time (s)": clustering_time,
    "Number of Clusters": len(set(agglomerative_labels)),
    "Calinski-Harabasz Index": calinski_harabasz_score(x_test_encoded, agglomerative_labels),
    "Davies-Bouldin Index": davies_bouldin_score(x_test_encoded, agglomerative_labels),
    "Silhouette Score": silhouette_score(x_test_encoded, agglomerative_labels),
    "Adjusted Mutual Information (AMI)": adjusted_mutual_info_score(y_test, agglomerative_labels)
}])], ignore_index=True)

# Display the results
print(results_df)

#10o ερώτημα για PCA
import matplotlib.pyplot as plt
import numpy as np

def plot_cluster_results_grid(labels, algorithm_name, indices_to_display, num_samples=4):
    """
    Displays images in a grid for the selected classes and their clustering labels.
    """
    rows = len(indices_to_display)  # Number of classes
    cols = num_samples             # Number of images per class

    plt.figure(figsize=(cols * 2, rows * 2))

    for row_idx, class_idx in enumerate(indices_to_display):
        # Find all images belonging to this class
        indices = np.where(y_test == class_idx)[0]
        selected_indices = np.random.choice(indices, size=num_samples, replace=False)

        for col_idx, img_index in enumerate(selected_indices):
            original_image = x_test[img_index]
            cluster_label = labels[img_index]

            # Plot the image
            plt.subplot(rows, cols, row_idx * cols + col_idx + 1)
            plt.imshow(original_image, cmap='gray')
            plt.axis('off')
            plt.title(f"Class: {class_idx}\nCluster: {cluster_label}")

    plt.suptitle(f"Clustering Results for Selected Classes - {algorithm_name}", fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

# Plot results for each clustering algorithm
plot_cluster_results_grid(kmeans_labels, "MiniBatch KMeans", indices_to_display=[0, 1, 2, 3])
plot_cluster_results_grid(dbscan_labels, "DBSCAN", indices_to_display=[0, 1, 2, 3])
plot_cluster_results_grid(agglomerative_labels, "Agglomerative Clustering", indices_to_display=[0, 1, 2, 3])

#3o ερώτημα για SAE
import numpy as np
from tensorflow.keras import layers, models

# Reshape δεδομένων
x_train = x_train.reshape(-1, 28 * 28)
x_val = x_val.reshape(-1, 28 * 28)
x_test = x_test.reshape(-1, 28 * 28)

# Δημιουργία Autoencoder
encoding_dim = 50  # Διαστάσεις μετά το encoding

# Encoder
input_img = layers.Input(shape=(28 * 28,))
encoded = layers.Dense(128, activation='relu')(input_img)
encoded = layers.Dense(encoding_dim, activation='relu')(encoded)

# Decoder
decoded = layers.Dense(128, activation='relu')(encoded)
decoded = layers.Dense(28 * 28, activation='sigmoid')(decoded)

# Ορισμός Autoencoder
autoencoder = models.Model(input_img, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

# Εκπαίδευση Autoencoder
autoencoder.fit(
    x_train, x_train,
    epochs=50,
    batch_size=256,
    shuffle=True,
    validation_data=(x_val, x_val)
)


# Ορισμός του Encoder
encoder = models.Model(input_img, encoded)

# Dimensionality Reduction
x_train_reduced = encoder.predict(x_train)
x_val_reduced = encoder.predict(x_val)
x_test_reduced = encoder.predict(x_test)

# Εμφάνιση των σχημάτων
print("Αρχικό σχήμα train data:", x_train.shape)
print("Νέο σχήμα μετά το SAE (train data):", x_train_reduced.shape)
print("Νέο σχήμα μετά το SAE (validation data):", x_val_reduced.shape)
print("Νέο σχήμα μετά το SAE (test data):", x_test_reduced.shape)

#4o ερώτημα για SAE
import matplotlib.pyplot as plt
import numpy as np

# Function to get random images for each class
def get_random_images_per_class(x_data, y_data, classes=10):
    selected_images = []
    for class_label in range(classes):
        indices = np.where(y_data == class_label)[0]
        random_index = np.random.choice(indices)
        selected_images.append(x_data[random_index])
    return np.array(selected_images)



# Get random images from the test set (one for each class)
random_images = get_random_images_per_class(x_test.reshape(-1, 28, 28), y_test)

# Χρήση του SAE για ανακατασκευή εικόνων
random_images_flattened = random_images.reshape(random_images.shape[0], -1)
encoded_images = encoder.predict(random_images_flattened)
reconstructed_images_flattened = autoencoder.predict(random_images_flattened)  # Decode using the autoencoder
reconstructed_images = reconstructed_images_flattened.reshape(random_images.shape[0], 28, 28)  # Reshape to original dimensions


 #Original and reconstructed images side by side
fig, axes = plt.subplots(2, 10, figsize=(20, 5))

for i in range(10):

# Original image
    axes[0, i].imshow(random_images[i], cmap="gray")
    axes[0, i].set_title(f"Class {i}")
    axes[0, i].axis("off")

    # Reconstructed image
    axes[1, i].imshow(reconstructed_images[i], cmap="gray")
    axes[1, i].set_title(f"Reconstructed {i}")
    axes[1, i].axis("off")

plt.tight_layout()
plt.show()

#5o ερώτημα για SAE
import matplotlib.pyplot as plt
import numpy as np

# Δημιουργία Scatter Plot για τα δεδομένα μετά τη μείωση διάστασης
plt.figure(figsize=(10, 6))

# Χρήση των πρώτων 2 διαστάσεων από το μειωμένο δεδομένο
x_train_reduced_2d = x_train_reduced[:, :2]  # Χρησιμοποιούμε τις πρώτες 2 διαστάσεις

# Δημιουργία scatter plot με βάση τις ετικέτες (classes)
plt.scatter(x_train_reduced_2d[:, 0], x_train_reduced_2d[:, 1], c=y_train, cmap='viridis', alpha=0.5)

# Προσθήκη τίτλων και ετικετών στους άξονες
plt.title("Dimensionality Reduction using SAE (First 2 Components)", fontsize=16)
plt.xlabel("Component 1")
plt.ylabel("Component 2")

# Προσθήκη της colorbar για την αναγνώριση των κατηγοριών
plt.colorbar(label='Class Label')

# Εμφάνιση του γραφήματος
plt.show()

#6o ερώτημα για SAE
# 1. Κανονικοποιούμε τα test data (προβλέπουμε την κλίμακα των τιμών από 0 έως 1)
x_test_normalized = x_test / 255.0

# 2. Αναδιάρθρωση των test data σε μονοδιάστατο πίνακα (784 διαστάσεις) για να ταιριάζει με το AutoEncoder
x_test_reshaped = x_test_normalized.reshape(-1, 28 * 28)

# 3. Κωδικοποιούμε τα test data χρησιμοποιώντας το encoder του AutoEncoder
encoded_test_data = encoder.predict(x_test_reshaped)

# 4. Εκτύπωση των διαστάσεων του αποτελέσματος για επιβεβαίωση
print("Shape of encoded test data:", encoded_test_data.shape)

#7o ερώτημα για SAE
# Χρησιμοποιούμε το encoded_test_data_sae που παράχθηκε από τον encoder του SAE
data_for_clustering = encoded_test_data # Δεδομένα από το encoder του SAE

# 1. MiniBatch K-Means Clustering
from sklearn.cluster import MiniBatchKMeans
minibatch_kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
minibatch_labels = minibatch_kmeans.fit_predict(data_for_clustering)
print("MiniBatch K-Means labels:", minibatch_labels[:10])

# 2. DBSCAN Clustering
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=0.1, min_samples=15)
dbscan_labels = dbscan.fit_predict(data_for_clustering)
print("DBSCAN labels:", dbscan_labels[:10])

# 3. Agglomerative Clustering
from sklearn.cluster import AgglomerativeClustering
agg_clustering = AgglomerativeClustering(n_clusters=10)
agg_labels = agg_clustering.fit_predict(data_for_clustering)
print("Agglomerative Clustering labels:", agg_labels[:10])

# Αριθμός των clusters
print("Number of clusters from MiniBatch KMeans:", len(np.unique(minibatch_labels)))
print("Number of clusters from DBSCAN:", len(np.unique(dbscan_labels[dbscan_labels != -1])))  # Αγνοούμε το -1 για τα outliers
print("Number of clusters from Agglomerative Clustering:", len(np.unique(agg_labels)))

#8o ερώτημα για SAE
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score, adjusted_mutual_info_score
from sklearn.cluster import MiniBatchKMeans, DBSCAN, AgglomerativeClustering
import numpy as np

# Επιλογή της τεχνικής dimensionality reduction (SAE)
data_for_clustering = encoded_test_data

# Αποτελέσματα σε λεξικό
results = {}

# 1. MiniBatchKMeans
minibatch_kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
minibatch_kmeans_labels = minibatch_kmeans.fit_predict(data_for_clustering)

results["Mini Batch KMeans"] = {
    "Calinski-Harabasz": calinski_harabasz_score(data_for_clustering, minibatch_kmeans_labels),
    "Davies-Bouldin": davies_bouldin_score(data_for_clustering, minibatch_kmeans_labels),
    "Silhouette": silhouette_score(data_for_clustering, minibatch_kmeans_labels),
    "AMI": adjusted_mutual_info_score(y_test, minibatch_kmeans_labels),  # Adjusted Mutual Information
    "Number of Clusters": len(np.unique(minibatch_kmeans_labels)),
}

# 2. DBSCAN
dbscan = DBSCAN(eps=0.1, min_samples=15)  # Προσαρμόστε τις παραμέτρους ανάλογα με το dataset
dbscan_labels = dbscan.fit_predict(data_for_clustering)

# Ελέγχουμε αν ο DBSCAN παρήγαγε τουλάχιστον δύο clusters
if len(set(dbscan_labels)) > 1:
    results["DBSCAN"] = {
        "Calinski-Harabasz": calinski_harabasz_score(data_for_clustering, dbscan_labels),
        "Davies-Bouldin": davies_bouldin_score(data_for_clustering, dbscan_labels),
        "Silhouette": silhouette_score(data_for_clustering, dbscan_labels),
        "AMI": adjusted_mutual_info_score(y_test, dbscan_labels),  # Adjusted Mutual Information
        "Number of Clusters": len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0),  # Αφαιρούμε τα noise points
    }
else:
    results["DBSCAN"] = "Not enough clusters formed for metrics computation."

# 3. Agglomerative Clustering
agglomerative = AgglomerativeClustering(n_clusters=10)
agglomerative_labels = agglomerative.fit_predict(data_for_clustering)

results["Agglomerative Clustering"] = {
    "Calinski-Harabasz": calinski_harabasz_score(data_for_clustering, agglomerative_labels),
    "Davies-Bouldin": davies_bouldin_score(data_for_clustering, agglomerative_labels),
    "Silhouette": silhouette_score(data_for_clustering, agglomerative_labels),
    "AMI": adjusted_mutual_info_score(y_test, agglomerative_labels),  # Adjusted Mutual Information
    "Number of Clusters": len(set(agglomerative_labels)),
}

# Εκτύπωση των αποτελεσμάτων
for method, metrics in results.items():
    print(f"\nClustering Method: {method}")
    if isinstance(metrics, dict):
        for metric, value in metrics.items():
            print(f"{metric}: {value}")
    else:
        print(metrics)

#9o ερώτημα για SAE
import pandas as pd
import time
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score, adjusted_mutual_info_score

# Δημιουργία ενός άδειου DataFrame
results_df = pd.DataFrame(columns=[
    "Dim_Red_Technique",
    "Clustering_Algorithm",
    "Dim_Red_Time",
    "Clustering_Time",
    "Num_Clusters",
    "Calinski_Harabasz",
    "Davies_Bouldin",
    "Silhouette_Score",
    "Adjusted Mutual Information_Metric"
])

# Παράδειγμα για το SAE με MiniBatch KMeans
dim_red_technique = "SAE"
clustering_algorithm = "MiniBatch KMeans"

# Υπολογισμός χρόνου για Dimensionality Reduction
dim_red_start = time.time()
# Dimensionality reduction (π.χ. χρήση του encoder)
encoded_data = encoder.predict(x_test_normalized.reshape(-1, 28 * 28))
dim_red_time = time.time() - dim_red_start

# Υπολογισμός χρόνου για Clustering
clustering_start = time.time()
from sklearn.cluster import MiniBatchKMeans
kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
kmeans_labels = kmeans.fit_predict(encoded_data)
clustering_time = time.time() - clustering_start

# Υπολογισμός των μετρικών
num_clusters = len(set(kmeans_labels)) - (1 if -1 in kmeans_labels else 0)  # Αφαιρούμε το -1 αν υπάρχει (DBSCAN)
calinski_harabasz = calinski_harabasz_score(encoded_data, kmeans_labels)
davies_bouldin = davies_bouldin_score(encoded_data, kmeans_labels)
silhouette = silhouette_score(encoded_data, kmeans_labels)
ami_metric = adjusted_mutual_info_score(y_test, kmeans_labels)

# Καταχώρηση στο DataFrame
results_df = pd.DataFrame([{
    "Dim_Red_Technique": dim_red_technique,
    "Clustering_Algorithm": clustering_algorithm,
    "Dim_Red_Time": dim_red_time,
    "Clustering_Time": clustering_time,
    "Num_Clusters": num_clusters,
    "Calinski_Harabasz": calinski_harabasz,
    "Davies_Bouldin": davies_bouldin,
    "Silhouette_Score": silhouette,
    "Adjusted Mutual Information_Metric": ami_metric
}])
results_df = pd.concat([results_df, results_df], ignore_index=True)

# Εμφάνιση του DataFrame
print(results_df)

#10o ερώτημα για SAE
import matplotlib.pyplot as plt
import numpy as np

def plot_cluster_results_grid(labels, algorithm_name, indices_to_display, num_samples=4):
    """
    Displays images in a grid for the selected classes and their clustering labels.
    """
    rows = len(indices_to_display)  # Number of classes
    cols = num_samples             # Number of images per class

    plt.figure(figsize=(cols * 2, rows * 2))

    for row_idx, class_idx in enumerate(indices_to_display):
        # Find all images belonging to this class
        indices = np.where(y_test == class_idx)[0]
        selected_indices = np.random.choice(indices, size=num_samples, replace=False)

        for col_idx, img_index in enumerate(selected_indices):
            original_image = x_test[img_index].reshape(28, 28)
            cluster_label = labels[img_index]

            # Plot the image
            plt.subplot(rows, cols, row_idx * cols + col_idx + 1)
            plt.imshow(original_image, cmap='gray')
            plt.axis('off')
            plt.title(f"Class: {class_idx}\nCluster: {cluster_label}")

    plt.suptitle(f"Clustering Results for Selected Classes - {algorithm_name}", fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

# 1. Κανονικοποίηση και αναδιάταξη των δεδομένων για χρήση στο SAE
subset_images_normalized = x_test / 255.0
subset_images_normalized =x_test_normalized.reshape(-1, 28 * 28)

# 2. Κωδικοποίηση με το SAE (χρησιμοποιούμε το encoder που έχουμε ήδη εκπαιδεύσει)
subset_encoded = encoder.predict(subset_images_normalized)

# 3. Εφαρμογή clustering
# MiniBatch KMeans
minibatch_kmeans = MiniBatchKMeans(n_clusters=10, random_state=42)
minibatch_labels = minibatch_kmeans.fit_predict(subset_encoded)

# DBSCAN
dbscan = DBSCAN(eps=0.1, min_samples=15)
dbscan_labels = dbscan.fit_predict(subset_encoded)

# Agglomerative Clustering
agglomerative = AgglomerativeClustering(n_clusters=10)
agglo_labels = agglomerative.fit_predict(subset_encoded)

# 4. Εκτύπωση αποτελεσμάτων clustering για τις επιλεγμένες κατηγορίες
plot_cluster_results_grid(minibatch_labels, "MiniBatch KMeans", indices_to_display=[0, 1, 2, 3])
plot_cluster_results_grid(dbscan_labels, "DBSCAN", indices_to_display=[0, 1, 2, 3])
plot_cluster_results_grid(agglomerative_labels, "Agglomerative Clustering", indices_to_display=[0, 1, 2, 3])

#3o ερώτημα για Factor Analysis
from sklearn.decomposition import FactorAnalysis
import numpy as np

# Reshape the data for Factor Analysis (it expects 2D array: samples x features)
x_train_flat = x_train.reshape(x_train.shape[0], -1)
x_val_flat = x_val.reshape(x_val.shape[0], -1)
x_test_flat = x_test.reshape(x_test.shape[0], -1)

# Apply Factor Analysis
n_components = 50  # Adjust the number of components as needed
factor_analysis = FactorAnalysis(n_components=n_components, random_state=42)

# Fit the model on the training data and transform it
x_train_reduced = factor_analysis.fit_transform(x_train_flat)
x_val_reduced = factor_analysis.transform(x_val_flat)
x_test_reduced = factor_analysis.transform(x_test_flat)

# Display the shapes of the reduced datasets
print("Reduced train set shape:", x_train_reduced.shape)
print("Reduced validation set shape:", x_val_reduced.shape)
print("Reduced test set shape:", x_test_reduced.shape)

#4o ερώτημα για Factor Analysis
import matplotlib.pyplot as plt
import numpy as np

# Επιλογή τυχαίας εικόνας από κάθε κλάση
unique_classes = np.unique(y_train)
sample_images = []

for class_label in unique_classes:
    # Επιλογή τυχαίας εικόνας από την κλάση
    class_indices = np.where(y_train == class_label)[0]
    random_index = np.random.choice(class_indices)
    sample_images.append((x_train[random_index].reshape(28, 28), class_label))

# Δημιουργία γραφικής παράστασης
fig, axes = plt.subplots(len(unique_classes), 2, figsize=(10, 2 * len(unique_classes)))

for i, (image, label) in enumerate(sample_images):
    # Αρχική εικόνα
    ax = axes[i, 0]
    ax.imshow(image, cmap="gray")
    ax.set_title(f"Class {label}")
    ax.axis('off')

    # Ανακατασκευή της εικόνας
    image_flat = image.reshape(1, -1)  # Μετατροπή της εικόνας σε επίπεδο πίνακα (1D)

    image_reconstructed = np.dot(factor_analysis.transform(image_flat), factor_analysis.components_) + factor_analysis.mean_

    image_reconstructed = image_reconstructed.reshape(28, 28)  # Επαναφορά στο σχήμα 28x28

    # Ανακατασκευασμένη εικόνα
    ax = axes[i, 1]
    ax.imshow(image_reconstructed, cmap="gray")
    ax.set_title(f"Reconstructed Class {label}")
    ax.axis('off')

plt.tight_layout()
plt.show()

#5o ερώτημα για Factor Analysis
import matplotlib.pyplot as plt

# Επιλογή των δύο πρώτων συνιστωσών από τα μειωμένα δεδομένα
x_train_2d = x_train_reduced[:, :2]

# Δημιουργία scatter plot
plt.figure(figsize=(10, 8))
scatter = plt.scatter(x_train_2d[:, 0], x_train_2d[:, 1], c=y_train, cmap='tab10', alpha=0.7, s=10)
plt.title("2D Scatter Plot of Reduced Dimensions (Factor Analysis)", fontsize=14)
plt.xlabel("Component 1")
plt.ylabel("Component 2")
plt.colorbar(scatter, label="Class Label")
plt.grid(True, alpha=0.3)
plt.show()

#6o ερώτημα για Factor Analysis
# Εφαρμογή της τεχνικής Factor Analysis στα test data
x_test_encoded = factor_analysis.transform(x_test_flat)

# Εμφάνιση των σχημάτων πριν και μετά την κωδικοποίηση
print("Original test set shape:", x_test_flat.shape)
print("Encoded test set shape:", x_test_encoded.shape)

#7o ερώτημα για Factor Analysis
from sklearn.cluster import MiniBatchKMeans, DBSCAN, AgglomerativeClustering
import numpy as np

# MiniBatch KMeans Clustering
n_clusters = 10  # Υποθέτουμε ότι υπάρχουν 10 κλάσεις
kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42)
kmeans_labels = kmeans.fit_predict(x_test_encoded)
kmeans_unique_clusters = len(np.unique(kmeans_labels))

# DBSCAN Clustering

dbscan = DBSCAN(eps=3, min_samples=5)
dbscan_labels = dbscan.fit_predict(x_test_encoded)
dbscan_unique_clusters = len(set(dbscan_labels) - {-1})  # Αφαιρούμε το noise (-1)

# Agglomerative Clustering
agglo = AgglomerativeClustering(n_clusters=n_clusters)
agglo_labels = agglo.fit_predict(x_test_encoded)
agglo_unique_clusters = len(np.unique(agglo_labels))

# Εμφάνιση αποτελεσμάτων
print("MiniBatch KMeans Clustering:")
print(f"Number of clusters: {kmeans_unique_clusters}")
print(f"Cluster labels: {kmeans_labels[:20]}")

print("\nDBSCAN Clustering:")
print(f"Number of clusters: {dbscan_unique_clusters}")
print(f"Cluster labels: {dbscan_labels[:20]}")

print("\nAgglomerative Clustering:")
print(f"Number of clusters: {agglo_unique_clusters}")
print(f"Cluster labels: {agglo_labels[:20]}")

#8o ερώτημα για Factor Analysis
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score, adjusted_mutual_info_score

# Υπολογισμός μετρικών για MiniBatchKMeans
print("MiniBatch KMeans Metrics:")
ch_score_kmeans = calinski_harabasz_score(x_test_encoded, kmeans_labels)
db_score_kmeans = davies_bouldin_score(x_test_encoded, kmeans_labels)
silhouette_kmeans = silhouette_score(x_test_encoded, kmeans_labels)
ami_kmeans = adjusted_mutual_info_score(y_test, kmeans_labels)

print(f"Calinski-Harabasz Index: {ch_score_kmeans}")
print(f"Davies-Bouldin Index: {db_score_kmeans}")
print(f"Silhouette Score: {silhouette_kmeans}")
print(f"Adjusted Mutual Information (AMI): {ami_kmeans}")

# Υπολογισμός μετρικών για DBSCAN (χωρίς noise points -1)
print("\nDBSCAN Metrics:")
valid_dbscan_indices = dbscan_labels != -1  # Απομακρύνουμε τα noise points
if np.any(valid_dbscan_indices):
    ch_score_dbscan = calinski_harabasz_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    db_score_dbscan = davies_bouldin_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    silhouette_dbscan = silhouette_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    ami_dbscan = adjusted_mutual_info_score(y_test[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])

    print(f"Calinski-Harabasz Index: {ch_score_dbscan}")
    print(f"Davies-Bouldin Index: {db_score_dbscan}")
    print(f"Silhouette Score: {silhouette_dbscan}")
    print(f"Adjusted Mutual Information (AMI): {ami_dbscan}")
else:
    print("DBSCAN did not produce valid clusters (all points are noise).")

# Υπολογισμός μετρικών για Agglomerative Clustering
print("\nAgglomerative Clustering Metrics:")
ch_score_agglo = calinski_harabasz_score(x_test_encoded, agglo_labels)
db_score_agglo = davies_bouldin_score(x_test_encoded, agglo_labels)
silhouette_agglo = silhouette_score(x_test_encoded, agglo_labels)
ami_agglo = adjusted_mutual_info_score(y_test, agglo_labels)

print(f"Calinski-Harabasz Index: {ch_score_agglo}")
print(f"Davies-Bouldin Index: {db_score_agglo}")
print(f"Silhouette Score: {silhouette_agglo}")
print(f"Adjusted Mutual Information (AMI): {ami_agglo}")

#9o ερώτημα για Factor Analysis
import pandas as pd
import time

# Δημιουργία κενού DataFrame για την αποθήκευση των αποτελεσμάτων
results_df = pd.DataFrame(columns=[
    "Dimensionality Reduction", "Clustering Algorithm", "Dim. Red. Time (s)",
    "Clustering Time (s)", "Number of Clusters",
    "Calinski-Harabasz Index", "Davies-Bouldin Index",
    "Silhouette Score", "Adjusted Mutual Information (AMI)"
])

# Εισαγωγή αποτελεσμάτων στο DataFrame
def add_results_to_df(dim_red_name, clustering_name, dim_red_time, clustering_time,
                      n_clusters, ch_index, db_index, silhouette, ami):
    global results_df
    new_row = pd.DataFrame([{
        "Dimensionality Reduction": dim_red_name,
        "Clustering Algorithm": clustering_name,
        "Dim. Red. Time (s)": dim_red_time,
        "Clustering Time (s)": clustering_time,
        "Number of Clusters": n_clusters,
        "Calinski-Harabasz Index": ch_index,
        "Davies-Bouldin Index": db_index,
        "Silhouette Score": silhouette,
        "Adjusted Mutual Information (AMI)": ami
    }])
    results_df = pd.concat([results_df, new_row], ignore_index=True)

# Υπολογισμός χρόνων και καταχώρηση για MiniBatchKMeans
start_dim_red = time.time()
x_test_encoded = factor_analysis.transform(x_test_flat)
dim_red_time = time.time() - start_dim_red

start_clustering = time.time()
kmeans_labels = kmeans.fit_predict(x_test_encoded)
clustering_time = time.time() - start_clustering

ch_index = calinski_harabasz_score(x_test_encoded, kmeans_labels)
db_index = davies_bouldin_score(x_test_encoded, kmeans_labels)
silhouette = silhouette_score(x_test_encoded, kmeans_labels)
ami = adjusted_mutual_info_score(y_test, kmeans_labels)
n_clusters = len(set(kmeans_labels))

add_results_to_df("Factor Analysis", "MiniBatch KMeans", dim_red_time, clustering_time,
                  n_clusters, ch_index, db_index, silhouette, ami)

# Υπολογισμός χρόνων και καταχώρηση για DBSCAN
start_clustering = time.time()
dbscan_labels = dbscan.fit_predict(x_test_encoded)
clustering_time = time.time() - start_clustering

valid_dbscan_indices = dbscan_labels != -1
if np.any(valid_dbscan_indices):
    ch_index = calinski_harabasz_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    db_index = davies_bouldin_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    silhouette = silhouette_score(x_test_encoded[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    ami = adjusted_mutual_info_score(y_test[valid_dbscan_indices], dbscan_labels[valid_dbscan_indices])
    n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
else:
    ch_index = db_index = silhouette = ami = np.nan
    n_clusters = 0

add_results_to_df("Factor Analysis", "DBSCAN", dim_red_time, clustering_time,
                  n_clusters, ch_index, db_index, silhouette, ami)

# Υπολογισμός χρόνων και καταχώρηση για Agglomerative Clustering
start_clustering = time.time()
agglo_labels = agglo.fit_predict(x_test_encoded)
clustering_time = time.time() - start_clustering

ch_index = calinski_harabasz_score(x_test_encoded, agglo_labels)
db_index = davies_bouldin_score(x_test_encoded, agglo_labels)
silhouette = silhouette_score(x_test_encoded, agglo_labels)
ami = adjusted_mutual_info_score(y_test, agglo_labels)
n_clusters = len(set(agglo_labels))

add_results_to_df("Factor Analysis", "Agglomerative Clustering", dim_red_time, clustering_time,
                  n_clusters, ch_index, db_index, silhouette, ami)

# Εμφάνιση αποτελεσμάτων
print(results_df)

#10o ερώτημα για Factor Analysis
import matplotlib.pyplot as plt
import numpy as np

def plot_cluster_results_grid(labels, algorithm_name, indices_to_display, num_samples=4):
    """
    Displays images in a grid for the selected classes and their clustering labels.
    """
    rows = len(indices_to_display)  # Number of classes
    cols = num_samples             # Number of images per class

    plt.figure(figsize=(cols * 2, rows * 2))

    for row_idx, class_idx in enumerate(indices_to_display):
        # Find all images belonging to this class
        indices = np.where(y_test == class_idx)[0]
        selected_indices = np.random.choice(indices, size=num_samples, replace=False)

        for col_idx, img_index in enumerate(selected_indices):
            # Εξασφαλίζουμε ότι το index δεν ξεπερνά τα διαθέσιμα δεδομένα
            if img_index < len(labels):
                original_image = x_test[img_index].reshape(28, 28)
                cluster_label = labels[img_index]

                # Plot the image
                plt.subplot(rows, cols, row_idx * cols + col_idx + 1)
                plt.imshow(original_image, cmap='gray')
                plt.axis('off')
                plt.title(f"Class: {class_idx}\nCluster: {cluster_label}")

    plt.suptitle(f"Clustering Results for Selected Classes - {algorithm_name}", fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

# Παρουσίαση αποτελεσμάτων για MiniBatch KMeans με Factor Analysis
print("MiniBatch KMeans Results using Factor Analysis:")
plot_cluster_results_grid(kmeans_labels, "MiniBatch KMeans", indices_to_display=[0, 1, 2, 3])

# Παρουσίαση αποτελεσμάτων για DBSCAN με Factor Analysis
print("DBSCAN Results using Factor Analysis:")
valid_dbscan_indices = dbscan_labels != -1
if np.any(valid_dbscan_indices):
    plot_cluster_results_grid(dbscan_labels[valid_dbscan_indices], "DBSCAN", indices_to_display=[0, 1, 2, 3])
else:
    print("DBSCAN did not form any valid clusters to display.")

# Παρουσίαση αποτελεσμάτων για Agglomerative Clustering με Factor Analysis
print("Agglomerative Clustering Results using Factor Analysis:")
plot_cluster_results_grid(agglo_labels, "Agglomerative Clustering", indices_to_display=[0, 1, 2, 3])